### ISSUE TITLE
Incorrect size for DEC L instruction

### ISSUE THREAD

**Issue by mrcook** [tstih/bugz#1]
Hi, it looks like `DEC L` instruction size is incorrect (https://github.com/tstih/bugz/blob/master/inst_set.c#L69):

```
{ 0x0000002D, 0x00000001, "DEC  L",                 2, 4,  0  },
```

**Comment by mrcook** [comment]
I noticed something else in the instructions; there is a missing character in the mnemonic:
```
{ 0x00000008, 0x00000001, "EX   AF,AF",             1, 4,  0  },
```

The shadow register is missing its apostrophe: `AF,AF'`

**Comment by tstih** [comment]
Hi Michael. Good find, thank you. Both fixes were applied.
